parameters:
    structure.generator.class: Sfynx\DddGeneratorBundle\Generator\Bundle\DddBundleGenerator
    structure.generator.command.class: Sfynx\DddGeneratorBundle\Command\GenerateDddStructureCommand

services:
    api.generator:
        class: %structure.generator.class%

    structure.generator.command:
        class: %structure.generator.command.class%
        calls:
          - [setGenerator, ["@api.generator"]]
        tags:
            -  { name: console.command }